name: tests

on:
  push:
    paths: 
      - server.cpp
      - sender.cpp
      - .github/workflows/tests.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: bash
      run: |
	 TERM=xterm-256color bash run_test.sh -- test_server_build test_fail_server1 test_fail_server2 test_server_configuration
